use bevy::prelude::*;

mod components;
mod systems;

use systems::{customer::*, gameplay::*, movement::*, setup::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(
            Update,
            (
                handle_click,
                move_to_target,
                fryer_cook,
                customer_serve,
                update_progress_bar,
                update_player_indicator,
                spawn_customers,
                despawn_customers,
                update_customer_indicators,
            ),
        )
        .run();
}
